# Generated by Django 3.1.2 on 2020-10-01 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=5)),
                ('corre_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_api.note')),
            ],
        ),
    ]
