# Generated by Django 3.1.2 on 2020-10-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0003_notechange_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notechange',
            name='corre_note',
            field=models.CharField(max_length=5),
        ),
    ]
