# Generated by Django 3.1.2 on 2020-10-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0004_auto_20201002_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notechange',
            name='created_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notechange',
            name='modified_date',
            field=models.CharField(max_length=100),
        ),
    ]
